import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/header'
import Footer from './components/footer/footer'
import { ViewTransitions } from 'next-view-transitions'
import LocomotiveWrapper from './components/scroller'

import PreloaderWrapper from './components/preloader/preloaderWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'HP Lion Dance',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <ViewTransitions>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <LocomotiveWrapper>
          <PreloaderWrapper>
          {children}
          </PreloaderWrapper>
          </LocomotiveWrapper>
          <Footer />
        </body>
      </html>
    </ViewTransitions>
  )
}
